[tool.ruff]
line-length = 88
target-version = "py311"
extend-exclude = ["artifacts", ".venv"]

# Enable common rule sets
select = [
  "E",    # pycodestyle errors
  "F",    # pyflakes
  "I",    # isort
  "B",    # flake8-bugbear
  "UP",   # pyupgrade
  "C90",  # mccabe complexity
  "N",    # pep8-naming
  "PT",   # flake8-pytest-style
  "SIM",  # flake8-simplify
  "RUF",  # Ruff-specific rules
]

# Ignore specific rules if needed
ignore = ["B008"]  # example: don't warn on mutable default arguments

# Ruff formatter (black-compatible)
[tool.ruff.format]
quote-style = "double"

[tool.black]
line-length = 88
target-version = ['py311']
