repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5  # use latest tag
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 24.3.0  # or latest
    hooks:
      - id: black
        language_version: python3
